export   const packages = [
    {
      id: "bd-1",
      code: "bd",
      data: "1 GB ",
      dataAmount: "1 GB",
      validity: "7 days",
      voice: 10,
      text: 10,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "200",
          USD: "2",
          AED: "7",
        },
      },
    },
    {
      id: "bd-2",
      code: "bd",
      data: "2 GB ",
      dataAmount: "2 GB",
      validity: "15 days",
      voice: 20,
      text: 20,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "350",
          USD: "3.5",
          AED: "13",
        },
      },
    },
    {
      id: "bd-3",
      code: "bd",
      data: "3 GB",
      dataAmount: "3 GB",
      validity: "30 days",
      voice: 30,
      text: 30,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "500",
          USD: "5",
          AED: "18",
        },
      },
    },
    {
      id: "bd-4",
      code: "bd",
      data: "5 GB ",
      dataAmount: "5 GB",
      validity: "30 days",
      voice: 50,
      text: 50,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "750",
          USD: "7.5",
          AED: "27",
        },
      },
    },
    {
      id: "bd-5",
      code: "bd",
      data: "100 MB",
      dataAmount: "10 GB",
      validity: "30 days",
      voice: 100,
      text: 100,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "1200",
          USD: "12",
          AED: "44",
        },
      },
    },
    {
      id: "bd-6",
      code: "bd",
      data: "15 GB",
      dataAmount: "15 GB",
      validity: "45 days",
      voice: 150,
      text: 999,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "1700",
          USD: "17",
          AED: "62",
        },
      },
    },
    {
      id: "bd-7",
      code: "bd",
      data: "20 GB ",
      dataAmount: "20 GB",
      validity: "60 days",
      voice: 200,
      text: 999,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "2200",
          USD: "22",
          AED: "80",
        },
      },
    },
    {
      id: "bd-8",
      code: "bd",
      data: "Unlimited ",
      dataAmount: "25 GB",
      validity: "60 days",
      voice: 300,
      text: 999,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "2700",
          USD: "27",
          AED: "98",
        },
      },
    },
    {
      id: "bd-9",
      code: "bd",
      data: "30 GB",
      dataAmount: "30 GB",
      validity: "90 days",
      voice: 500,
      text: 999,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "3200",
          USD: "32",
          AED: "116",
        },
      },
    },
    {
      id: "bd-10",
      code: "bd",
      data: "Unlimited Data",
      dataAmount: "Unlimited",
      validity: "90 days",
      voice: 999,
      text: 999,
      coverage: "Bangladesh",
      status: "Active",
      prices: {
        recommended_retail_price: {
          BDT: "4500",
          USD: "45",
          AED: "165",
        },
      },
    },
  ];